# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = spineDemo
DESTDIR = ../Win32/Debug
QT += core opengl widgets gui
CONFIG += debug
DEFINES += QT_DLL QT_OPENGL_LIB QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug \
    spine-runtime/include
LIBS += -lopengl32 \
    -lglu32
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
CONFIG -= flat

HEADERS +=  spine-runtime/include/spine/Animation.h \
            spine-runtime/include/spine/BoneData.h \
            spine-runtime/include/spine/PathConstraint.h \
            spine-runtime/include/spine/Skin.h \
            spine-runtime/include/spine/AnimationState.h \
            spine-runtime/include/spine/BoundingBoxAttachment.h  \
            spine-runtime/include/spine/PathConstraintData.h \
            spine-runtime/include/spine/Slot.h \
            spine-runtime/include/spine/AnimationStateData.h \
            spine-runtime/include/spine/Event.h \
            spine-runtime/include/spine/RegionAttachment.h \
            spine-runtime/include/spine/SlotData.h \
            spine-runtime/include/spine/Atlas.h \
            spine-runtime/include/spine/EventData.h \
            spine-runtime/include/spine/Skeleton.h \
            spine-runtime/include/spine/TransformConstraint.h \
            spine-runtime/include/spine/AtlasAttachmentLoader.h \
            spine-runtime/include/spine/IkConstraint.h \
            spine-runtime/include/spine/SkeletonBinary.h \
            spine-runtime/include/spine/TransformConstraintData.h \
            spine-runtime/include/spine/Attachment.h \
            spine-runtime/include/spine/IkConstraintData.h \
            spine-runtime/include/spine/SkeletonBounds.h \
            spine-runtime/include/spine/VertexAttachment.h \
            spine-runtime/include/spine/AttachmentLoader.h \
            spine-runtime/include/spine/MeshAttachment.h \
            spine-runtime/include/spine/SkeletonData.h \
            spine-runtime/include/spine/extension.h \
            spine-runtime/include/spine/Bone.h \
            spine-runtime/include/spine/PathAttachment.h \
            spine-runtime/include/spine/SkeletonJson.h \
            spine-runtime/include/spine/spine.h \
            glwindow.h \
            glWindowProxy.h \
            spineVertex.h \
            spineParser.h

SOURCES +=  spine-runtime/src/spine/Animation.c \
            spine-runtime/src/spine/Bone.c \
            spine-runtime/src/spine/Json.c \
            spine-runtime/src/spine/Skeleton.c \
            spine-runtime/src/spine/SlotData.c \
            spine-runtime/src/spine/AnimationState.c \
            spine-runtime/src/spine/BoneData.c \
            spine-runtime/src/spine/Json.h \
            spine-runtime/src/spine/SkeletonBinary.c \
            spine-runtime/src/spine/TransformConstraint.c \
            spine-runtime/src/spine/AnimationStateData.c \
            spine-runtime/src/spine/BoundingBoxAttachment.c \
            spine-runtime/src/spine/MeshAttachment.c \
            spine-runtime/src/spine/SkeletonBounds.c \
            spine-runtime/src/spine/TransformConstraintData.c \
            spine-runtime/src/spine/Atlas.c \
            spine-runtime/src/spine/Event.c \
            spine-runtime/src/spine/PathAttachment.c \
            spine-runtime/src/spine/SkeletonData.c \
            spine-runtime/src/spine/VertexAttachment.c \
            spine-runtime/src/spine/AtlasAttachmentLoader.c \
            spine-runtime/src/spine/EventData.c \
            spine-runtime/src/spine/PathConstraint.c \
            spine-runtime/src/spine/SkeletonJson.c \
            spine-runtime/src/spine/extension.c \
            spine-runtime/src/spine/Attachment.c \
            spine-runtime/src/spine/IkConstraint.c \
            spine-runtime/src/spine/PathConstraintData.c \
            spine-runtime/src/spine/Skin.c \
            spine-runtime/src/spine/kvec.h \
            spine-runtime/src/spine/AttachmentLoader.c \
            spine-runtime/src/spine/IkConstraintData.c \
            spine-runtime/src/spine/RegionAttachment.c \
            spine-runtime/src/spine/Slot.c \
            glwindow.cpp \
            glWindowProxy.cpp \
            spineVertex.cpp \
            spineParser.cpp \
            main.cpp